name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.10
      with:
        version: "8.10"

    - name: Install pkg and deps
      run: raco pkg install --batch --auto buid{-lib,-test,}

    - name: Run tests
      run: raco test .
